vich_uploader:
    db_driver: orm

    mappings:
        shoe:
            uri_prefix: /images/shoe
            upload_destination: '%kernel.project_dir%/public/images/shoe'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
