<?php

namespace App\DataFixtures;

use App\Entity\Shoe;
use App\Entity\Cupboard;
use App\Entity\Member;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    // Defines reference names for instances of Member
    private const TEST_MEMBER_1 = 'test-member-1';
    private const TEST_MEMBER_2 = 'test-member-2';
    private const FABIEN = 'fabien';

    // Defines reference names for instances of Cupboard
    private const TEST_CUPBOARD_1 = 'test-cupboard-1';
    private const TEST_CUPBOARD_2 = 'test-cupboard-2';
    private const SMELLY_CUPBOARD = 'smelly-cupboard';

    /**
     * Generates initialization data for cupboards : [title, cupboard_reference]
     * @return \\Generator
     */
    private static function getCupboardsData()
    {
        yield ["Test Cupboard 1", self::TEST_MEMBER_1, self::TEST_CUPBOARD_1];
        yield ["Test Cupboard 2", self::TEST_MEMBER_2, self::TEST_CUPBOARD_2];

        yield ["Smelly Cupboard", self::FABIEN, self::SMELLY_CUPBOARD];
    }

    /**
     * Generates initialization data for shoes: [brand, model, cupboard_reference]
     * @return \\Generator
     */
    private static function getShoesData()
    {
        yield ["Test Brand 1", "", self::TEST_CUPBOARD_1];
        yield ["Test Brand 2", "Model 1", self::TEST_CUPBOARD_1];

        yield ["Kalenji", "Run Active", self::SMELLY_CUPBOARD];
        yield ["Kalenji", "kiprun XT7", self::SMELLY_CUPBOARD];
        yield ["Asics", "Gel-tarbuco 11", self::SMELLY_CUPBOARD];
        yield ["Quechua", "", self::SMELLY_CUPBOARD];
        yield ["Salomon", "X Ultra Mid 3 GTX", self::SMELLY_CUPBOARD];
    }

    /**
     * Generates initialization data for members: [name, age]
     * @return \\Generator
     */
    private static function getMembersData()
    {
        yield ["Test Member 1", 123, self::TEST_MEMBER_1];
        yield ["Test Member 2", 666, self::TEST_MEMBER_2];

        yield ["Fabien", 21, self::FABIEN];
    }

    public function load(ObjectManager $manager)
    {
        // $inventoryRepo = $manager->getRepository(Cupboard::class);

        foreach(self::getMembersData() as [$name, $age, $memberRreference]) {
            $member = new Member();
            $member->setName($name);
            $member->setAge($age);
            $manager->persist($member);
            $manager->flush();

            // Once the Member instance has been saved to DB
            // it has a valid ID generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($memberRreference, $member);
        }

        foreach (self::getCupboardsData() as [$name, $memberRreference, $cupboardReference]) {
            $cupboard = new Cupboard();
            $cupboard->setName($name);
            // Attribute cupboard to member
            $member = $this->getReference($memberRreference);
            $member->addCupboard($cupboard);
            $manager->persist($cupboard);
            $manager->flush();

            // Once the Cupboard instance has been saved to DB
            // it has a valid ID generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($cupboardReference, $cupboard);
        }

        foreach (self::getShoesData() as [$brand, $model, $cupboardReference]) {
            // Create new Shoes
            $shoe = new Shoe();
            $shoe->setBrand($brand);
            $shoe->setModel($model);
            // Put the Shoes in its Cupboard
            $cupboard = $this->getReference($cupboardReference);
            $cupboard->addShoe($shoe);

            // Requires ORM\OneToMany attribute on Cupboard::shoes has "cascade: ['persist']"
            $manager->persist($cupboard);
        }
        $manager->flush();
    }
}
